baseURL = "https://austinletson.github.io/"
languageCode = "en-us"
title = "\"Like punning, programming is a play on words.\" -Alan Perlis" 
theme="erblog"

[params]
    author = "Austin Letson"
    description = """
            Software Engineer, Writer, Runner.
            @NYC
            """
    portrait = "/img/prof_img.jpg"
    # logo = "//blog.ertuil.top/avater.png"
    bio = """
    <br />
    <br />
    <p> I am Austin. This is my website.</p>
    <br />
    <p>I am a interested in programing language design, editors, and limmericks. I am graduate of Georgia Tech with a degree in computer science.</p>

    <br />
    """
    copyright = "Copyright © 2020, Austin Letson with help from Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 7

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 8

[[menu.icon]]
    url = "mailto:aletson2357@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/austinletson/"
    name = "github"
    weight = 2 

[[menu.icon]]
    url = "https://www.linkedin.com/in/austin-letson-b57699135/"
    name = "linkedin"
    weight = 10

[[menu.icon]]
    url = ""
    name = "rss"
    weight = 10
